### ISSUE TITLE
Can I change the value of batch-size？

### ISSUE THREAD

**Issue by xyeahr** [Kongsea/FPN_TensorFlow#8]
Can I change the value of batch-size？If I change its value,  other values need to be modified at the same time？ Thanks！!

**Comment by Kongsea** [comment]
Of course you can, if you have enough GPU memory.

**Comment by xyeahr** [comment]
But when I changed it, I got this error：
Traceback (most recent call last):
  File "./tools/train.py", line 229, in <module>
    train()
  File "./tools/train.py", line 38, in train
    text=tf.shape(gtboxes_and_label_batch)[1])
  File "./tools/../libs/box_utils/show_box_in_tensor.py", line 59, in draw_box_with_color
    img_tensor = tf.squeeze(img_batch, 0)
  File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2630, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7862, in squeeze
    "Squeeze", input=input, squeeze_dims=axis, name=name)
  File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Can not squeeze dim[0], expected a dimension of 1, got 64 for 'draw_gtboxes/Squeeze' (op: 'Squeeze') with input shapes: [64,?,?,3].


What can I do？ I just started doing this project so I need your help.  Thanks a lot！

**Comment by xyeahr** [comment]
@Kongsea  But when I changed it, I got this error：
Traceback (most recent call last):
File "./tools/train.py", line 229, in
train()
File "./tools/train.py", line 38, in train
text=tf.shape(gtboxes_and_label_batch)[1])
File "./tools/../libs/box_utils/show_box_in_tensor.py", line 59, in draw_box_with_color
img_tensor = tf.squeeze(img_batch, 0)
File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2630, in squeeze
return gen_array_ops.squeeze(input, axis, name)
File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7862, in squeeze
"Squeeze", input=input, squeeze_dims=axis, name=name)
File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
op_def=op_def)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in init
control_input_ops)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
raise ValueError(str(e))
ValueError: Can not squeeze dim[0], expected a dimension of 1, got 64 for 'draw_gtboxes/Squeeze' (op: 'Squeeze') with input shapes: [64,?,?,3].

What can I do？ I just started doing this project so I need your help. Thanks a lot！

**Comment by Kongsea** [comment]
Sorry, it seems the original code only supports to set batch_size to be 1. Maybe you have to modify the code accordingly while changing the batch_size.

**Comment by xyeahr** [comment]
@Kongsea Thank you !  I'll try it.
